env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  max-len:
    - error
    - 120
  no-console:
    - warn
  no-shadow:
    - error
  quotes:
    - error
    - single
  semi:
    - error
    - never
