type:
  component:
    inputs:
      model: list

children:
  render: document/render

connections:
  model:
    render: model

defaults:
  model:
    - type: div
      attributes:
        style: 'font-size: 24px; font-weight: bold;'
      children:
        - Hello, world!
